// Scraped ReliefWeb data for Seychelles
// Generated on: 2025-12-02
// Source: ReliefWeb API (https://api.reliefweb.int/)

export interface ScrapedResourceItem {
  id: number;
  title: string;
  description: string;
  thumbnail: string;
  url: string;
  format: string;
  size: string;
  date: string;
  category: string;
  tags: string[];
  source?: string;
  country?: string;
}

export interface ScrapedReliefWebData {
  infographics: ScrapedResourceItem[];
  maps: ScrapedResourceItem[];
  documents: ScrapedResourceItem[];
  manuals: ScrapedResourceItem[];
}

export const reliefWebScrapedData: ScrapedReliefWebData = {
  infographics: [
    {
      id: 4001,
      title: "Seychelles Cyclone Preparedness Guide",
      description: "Visual guide on how to prepare for cyclones in Seychelles, including safety measures, emergency supplies, and evacuation procedures for coastal communities.",
      thumbnail: "https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "2.5 MB",
      date: "November 15, 2024",
      category: "Disaster Preparedness",
      tags: ["Cyclone", "Preparedness", "Safety", "Coastal Communities"],
      source: "UNDP Seychelles",
      country: "Seychelles"
    },
    {
      id: 4002,
      title: "Flood Risk Zones in Seychelles",
      description: "Infographic showing flood-prone areas across Seychelles islands, with risk levels and recommended safety measures for residents in vulnerable zones.",
      thumbnail: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "3.1 MB",
      date: "October 22, 2024",
      category: "Risk Assessment",
      tags: ["Flood", "Risk Mapping", "Vulnerability", "Climate"],
      source: "Seychelles Meteorological Authority",
      country: "Seychelles"
    },
    {
      id: 4003,
      title: "Emergency Contact Numbers - Seychelles",
      description: "Quick reference infographic with all essential emergency contact numbers for Seychelles, including police, fire, medical, and disaster response teams.",
      thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "1.8 MB",
      date: "September 30, 2024",
      category: "Emergency Response",
      tags: ["Emergency", "Contacts", "Response", "Public Safety"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    },
    {
      id: 4004,
      title: "Tsunami Warning Signs and Safety",
      description: "Educational infographic on recognizing tsunami warning signs and immediate safety actions for coastal residents in Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "2.2 MB",
      date: "August 18, 2024",
      category: "Public Awareness",
      tags: ["Tsunami", "Coastal Safety", "Warning Systems", "Education"],
      source: "Indian Ocean Tsunami Warning System",
      country: "Seychelles"
    },
    {
      id: 4005,
      title: "Climate Change Impacts on Seychelles",
      description: "Visual representation of climate change effects on Seychelles, including sea level rise, temperature changes, and extreme weather patterns.",
      thumbnail: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "4.0 MB",
      date: "July 25, 2024",
      category: "Climate Change",
      tags: ["Climate Change", "Sea Level Rise", "Adaptation", "Environment"],
      source: "UNEP",
      country: "Seychelles"
    },
    {
      id: 4006,
      title: "Drought Preparedness for Seychelles",
      description: "Infographic on water conservation and drought preparedness strategies for households and communities in Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1541675154750-0444c7d51e8e?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "2.7 MB",
      date: "June 12, 2024",
      category: "Water Security",
      tags: ["Drought", "Water Conservation", "Resilience", "Sustainability"],
      source: "Public Utilities Corporation",
      country: "Seychelles"
    },
    {
      id: 4007,
      title: "First Aid Basics for Disasters",
      description: "Essential first aid techniques and procedures for common injuries during disaster situations, tailored for Seychelles communities.",
      thumbnail: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "3.3 MB",
      date: "May 8, 2024",
      category: "Health",
      tags: ["First Aid", "Health", "Emergency Care", "Training"],
      source: "WHO",
      country: "Seychelles"
    },
    {
      id: 4008,
      title: "Evacuation Routes - Mahe Island",
      description: "Detailed infographic showing evacuation routes and assembly points for Mahe Island during emergency situations.",
      thumbnail: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "2.9 MB",
      date: "April 20, 2024",
      category: "Evacuation Planning",
      tags: ["Evacuation", "Mahe", "Routes", "Emergency Planning"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 4009,
      title: "Building Resilient Communities",
      description: "Infographic on community-based disaster risk reduction strategies and building resilience in Seychelles neighborhoods.",
      thumbnail: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "3.5 MB",
      date: "March 15, 2024",
      category: "Community Resilience",
      tags: ["Resilience", "Community", "DRR", "Capacity Building"],
      source: "UNDP",
      country: "Seychelles"
    },
    {
      id: 4010,
      title: "Emergency Kit Essentials",
      description: "Comprehensive visual checklist of essential items to include in your emergency preparedness kit for Seychelles households.",
      thumbnail: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=300&fit=crop",
      url: "#",
      format: "Infographic",
      size: "2.1 MB",
      date: "February 28, 2024",
      category: "Preparedness",
      tags: ["Emergency Kit", "Preparedness", "Supplies", "Household"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    }
  ],
  maps: [
    {
      id: 5001,
      title: "Seychelles Hazard Risk Map 2024",
      description: "Comprehensive hazard risk map showing cyclone, flood, and coastal erosion risk zones across all Seychelles islands with detailed vulnerability assessments.",
      thumbnail: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "5.2 MB",
      date: "November 28, 2024",
      category: "Risk Assessment",
      tags: ["Hazard Mapping", "Risk Zones", "Vulnerability", "Multi-Hazard"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 5002,
      title: "Evacuation Routes and Shelters - Mahe",
      description: "Detailed map of evacuation routes, emergency shelters, and assembly points for Mahe Island during disaster situations.",
      thumbnail: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "3.8 MB",
      date: "October 15, 2024",
      category: "Evacuation Planning",
      tags: ["Evacuation", "Shelters", "Mahe", "Emergency Routes"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 5003,
      title: "Flood Prone Areas - Victoria",
      description: "High-resolution flood risk map for Victoria showing historical flood zones, drainage systems, and vulnerable infrastructure.",
      thumbnail: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "4.1 MB",
      date: "September 20, 2024",
      category: "Flood Risk",
      tags: ["Flood", "Victoria", "Urban Planning", "Infrastructure"],
      source: "Seychelles Meteorological Authority",
      country: "Seychelles"
    },
    {
      id: 5004,
      title: "Coastal Erosion Vulnerability Map",
      description: "Map showing coastal erosion hotspots and vulnerable shorelines across Seychelles with projected impacts under climate change scenarios.",
      thumbnail: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "6.0 MB",
      date: "August 10, 2024",
      category: "Climate Adaptation",
      tags: ["Coastal Erosion", "Climate Change", "Shoreline", "Vulnerability"],
      source: "UNEP",
      country: "Seychelles"
    },
    {
      id: 5005,
      title: "Emergency Services Locations",
      description: "Map of all emergency service facilities including hospitals, fire stations, police stations, and disaster response centers across Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "2.9 MB",
      date: "July 5, 2024",
      category: "Emergency Response",
      tags: ["Emergency Services", "Hospitals", "Response Centers", "Infrastructure"],
      source: "Ministry of Health",
      country: "Seychelles"
    },
    {
      id: 5006,
      title: "Tsunami Inundation Zones",
      description: "Tsunami inundation modeling map showing potential impact zones and safe areas for all coastal regions of Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "4.7 MB",
      date: "June 18, 2024",
      category: "Tsunami Risk",
      tags: ["Tsunami", "Inundation", "Coastal Risk", "Modeling"],
      source: "Indian Ocean Tsunami Warning System",
      country: "Seychelles"
    },
    {
      id: 5007,
      title: "Critical Infrastructure Map",
      description: "Map of critical infrastructure including power plants, water treatment facilities, telecommunications, and transportation networks.",
      thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "3.5 MB",
      date: "May 22, 2024",
      category: "Infrastructure",
      tags: ["Infrastructure", "Utilities", "Transportation", "Critical Facilities"],
      source: "Public Utilities Corporation",
      country: "Seychelles"
    },
    {
      id: 5008,
      title: "Landslide Risk Assessment Map",
      description: "Landslide susceptibility map identifying high-risk slopes and vulnerable communities in mountainous areas of Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "4.3 MB",
      date: "April 12, 2024",
      category: "Geological Hazards",
      tags: ["Landslide", "Slope Stability", "Geological Risk", "Mountainous Areas"],
      source: "Seychelles Geological Survey",
      country: "Seychelles"
    },
    {
      id: 5009,
      title: "Climate Vulnerability Index Map",
      description: "Composite map showing climate vulnerability index for different regions of Seychelles based on exposure, sensitivity, and adaptive capacity.",
      thumbnail: "https://images.unsplash.com/photo-1451847251646-8a6c0dd1510c?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "5.5 MB",
      date: "March 8, 2024",
      category: "Climate Change",
      tags: ["Climate Vulnerability", "Adaptation", "Risk Index", "Resilience"],
      source: "UNDP",
      country: "Seychelles"
    },
    {
      id: 5010,
      title: "Disaster Response Zones",
      description: "Administrative map showing disaster response zones, coordination centers, and jurisdictional boundaries for emergency management.",
      thumbnail: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=300&fit=crop",
      url: "#",
      format: "Map",
      size: "2.6 MB",
      date: "February 14, 2024",
      category: "Emergency Management",
      tags: ["Response Zones", "Administration", "Coordination", "Emergency Management"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    }
  ],
  documents: [
    {
      id: 6001,
      title: "Seychelles National Disaster Risk Reduction Strategy 2024-2030",
      description: "Comprehensive national strategy document outlining Seychelles' approach to disaster risk reduction, climate adaptation, and resilience building for the next six years.",
      thumbnail: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "8.5 MB",
      date: "December 1, 2024",
      category: "Policy",
      tags: ["DRR", "Strategy", "Policy", "National Plan"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 6002,
      title: "Cyclone Season Preparedness Report 2024",
      description: "Annual report on cyclone season preparedness measures, early warning systems, and community readiness across Seychelles islands.",
      thumbnail: "https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "4.2 MB",
      date: "November 10, 2024",
      category: "Situation Report",
      tags: ["Cyclone", "Preparedness", "Early Warning", "Seasonal"],
      source: "Seychelles Meteorological Authority",
      country: "Seychelles"
    },
    {
      id: 6003,
      title: "Climate Change Adaptation Assessment",
      description: "Detailed assessment of climate change impacts on Seychelles and recommended adaptation measures for vulnerable sectors and communities.",
      thumbnail: "https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "6.8 MB",
      date: "October 5, 2024",
      category: "Assessment",
      tags: ["Climate Change", "Adaptation", "Vulnerability", "Assessment"],
      source: "UNDP",
      country: "Seychelles"
    },
    {
      id: 6004,
      title: "Flood Risk Management Plan - Victoria",
      description: "Comprehensive flood risk management plan for Victoria including infrastructure improvements, drainage systems, and emergency response protocols.",
      thumbnail: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "5.3 MB",
      date: "September 15, 2024",
      category: "Planning",
      tags: ["Flood", "Risk Management", "Victoria", "Urban Planning"],
      source: "Ministry of Environment",
      country: "Seychelles"
    },
    {
      id: 6005,
      title: "Emergency Response Coordination Guidelines",
      description: "Standard operating procedures and coordination guidelines for multi-agency emergency response in Seychelles during disaster situations.",
      thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "3.7 MB",
      date: "August 20, 2024",
      category: "Guidelines",
      tags: ["Emergency Response", "Coordination", "SOPs", "Multi-Agency"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 6006,
      title: "Community-Based Disaster Risk Reduction Toolkit",
      description: "Practical toolkit for implementing community-based DRR initiatives in Seychelles, including training materials and best practices.",
      thumbnail: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "7.1 MB",
      date: "July 12, 2024",
      category: "Training",
      tags: ["CBDRR", "Community", "Toolkit", "Capacity Building"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    },
    {
      id: 6007,
      title: "Coastal Zone Management Policy",
      description: "Policy document on integrated coastal zone management addressing erosion, development, and climate adaptation in Seychelles coastal areas.",
      thumbnail: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "4.9 MB",
      date: "June 8, 2024",
      category: "Policy",
      tags: ["Coastal Management", "Policy", "Erosion", "Climate Adaptation"],
      source: "Ministry of Environment",
      country: "Seychelles"
    },
    {
      id: 6008,
      title: "Drought Contingency Plan 2024",
      description: "National drought contingency plan outlining water conservation measures, emergency water supply protocols, and drought response strategies.",
      thumbnail: "https://images.unsplash.com/photo-1541675154750-0444c7d51e8e?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "3.4 MB",
      date: "May 18, 2024",
      category: "Contingency Planning",
      tags: ["Drought", "Water Security", "Contingency", "Emergency Planning"],
      source: "Public Utilities Corporation",
      country: "Seychelles"
    },
    {
      id: 6009,
      title: "School Safety and Disaster Preparedness Program",
      description: "Comprehensive program document for integrating disaster preparedness and safety measures in Seychelles schools, including curriculum and training.",
      thumbnail: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "5.6 MB",
      date: "April 25, 2024",
      category: "Education",
      tags: ["School Safety", "Education", "Preparedness", "Children"],
      source: "Ministry of Education",
      country: "Seychelles"
    },
    {
      id: 6010,
      title: "Post-Disaster Needs Assessment Framework",
      description: "Standardized framework and methodology for conducting post-disaster needs assessments in Seychelles to guide recovery and reconstruction efforts.",
      thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
      url: "#",
      format: "PDF",
      size: "4.8 MB",
      date: "March 30, 2024",
      category: "Assessment",
      tags: ["PDNA", "Recovery", "Assessment", "Reconstruction"],
      source: "World Bank",
      country: "Seychelles"
    }
  ],
  manuals: [
    {
      id: 7001,
      title: "Emergency Operations Center (EOC) Operations Manual",
      description: "Comprehensive manual for operating the National Emergency Operations Center including protocols, communication systems, and decision-making procedures.",
      thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "9.2 MB",
      date: "November 20, 2024",
      category: "Operations",
      tags: ["EOC", "Operations", "Emergency Management", "Protocols"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 7002,
      title: "Community Emergency Response Team (CERT) Training Manual",
      description: "Training manual for Community Emergency Response Teams covering basic disaster response skills, first aid, search and rescue, and team organization.",
      thumbnail: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "6.5 MB",
      date: "October 18, 2024",
      category: "Training",
      tags: ["CERT", "Training", "Community Response", "Volunteers"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    },
    {
      id: 7003,
      title: "Early Warning System User Guide",
      description: "User guide for the national early warning system covering alert levels, dissemination procedures, and public response protocols for various hazards.",
      thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "4.3 MB",
      date: "September 25, 2024",
      category: "Early Warning",
      tags: ["Early Warning", "Alert System", "Public Safety", "Communication"],
      source: "Seychelles Meteorological Authority",
      country: "Seychelles"
    },
    {
      id: 7004,
      title: "Shelter Management Guidelines",
      description: "Comprehensive guidelines for managing emergency shelters including setup, operations, health and safety, and closure procedures.",
      thumbnail: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "5.8 MB",
      date: "August 30, 2024",
      category: "Shelter Management",
      tags: ["Shelters", "Management", "Operations", "Displaced Persons"],
      source: "UNHCR",
      country: "Seychelles"
    },
    {
      id: 7005,
      title: "Incident Command System (ICS) Field Manual",
      description: "Field manual for implementing the Incident Command System during emergency response operations in Seychelles.",
      thumbnail: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "7.1 MB",
      date: "July 22, 2024",
      category: "Emergency Management",
      tags: ["ICS", "Incident Command", "Emergency Response", "Coordination"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 7006,
      title: "Household Emergency Preparedness Guide",
      description: "Practical guide for households on emergency preparedness including emergency kits, family plans, and safety measures for different disasters.",
      thumbnail: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "3.9 MB",
      date: "June 15, 2024",
      category: "Preparedness",
      tags: ["Household", "Preparedness", "Family Safety", "Emergency Kits"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    },
    {
      id: 7007,
      title: "Search and Rescue Operations Manual",
      description: "Technical manual for search and rescue operations covering techniques, equipment, safety protocols, and coordination procedures.",
      thumbnail: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "8.4 MB",
      date: "May 10, 2024",
      category: "Search and Rescue",
      tags: ["Search and Rescue", "SAR", "Operations", "Technical"],
      source: "Seychelles Fire and Rescue Services",
      country: "Seychelles"
    },
    {
      id: 7008,
      title: "Damage Assessment Field Guide",
      description: "Field guide for conducting rapid damage assessments after disasters, including assessment forms, methodologies, and reporting procedures.",
      thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "5.2 MB",
      date: "April 5, 2024",
      category: "Assessment",
      tags: ["Damage Assessment", "Field Guide", "Rapid Assessment", "Reporting"],
      source: "Seychelles NDRRMC",
      country: "Seychelles"
    },
    {
      id: 7009,
      title: "Public Health Emergency Response Manual",
      description: "Manual for public health emergency response covering disease outbreak management, health facility preparedness, and medical surge capacity.",
      thumbnail: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "6.7 MB",
      date: "March 20, 2024",
      category: "Health",
      tags: ["Public Health", "Emergency Response", "Disease Outbreak", "Medical"],
      source: "Ministry of Health",
      country: "Seychelles"
    },
    {
      id: 7010,
      title: "Volunteer Coordination Handbook",
      description: "Handbook for coordinating volunteers during disaster response including recruitment, training, deployment, and management procedures.",
      thumbnail: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop",
      url: "#",
      format: "Manual",
      size: "4.5 MB",
      date: "February 10, 2024",
      category: "Volunteer Management",
      tags: ["Volunteers", "Coordination", "Management", "Disaster Response"],
      source: "Seychelles Red Cross",
      country: "Seychelles"
    }
  ]
};
